# Sci-ImageMiner 配置文件
inference:
  # 模型配置
  model:
    # Gemini 模型配置
    name: gemini-3.1-pro-preview
    base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions"
    api_key: "sk-e3bbc5ca49854de6b706562cfae5030d"
    
    # Qwen 模型配置
    # name: "qwen3.6-plus"
    # base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions"
    # api_key: "sk-e3bbc5ca49854de6b706562cfae5030d"  # 你的 API Key
    
    # proxy_url: "socks5://127.0.0.1:13659"

  # 数据配置
  data:
    root: "/Users/huangjing/Desktop/projects/Ai-Doc/AI_doc_new_features/RealDoc_Research/ALD-E-ImageMiner/icdar2026-competition-data/"
    split: "test"
#    split: "test"

  # 输出配置
  output:
    root: "../predictions/results_test_qwen3.6-plus_040801"

  # 并发配置
  concurrency:
    max_workers: 16  # 最大并发数
    request_delay: 0.5  # 请求间隔(秒)

  # 重试配置
  retry:
    max_retries: 3
    retry_delay: 1  # 重试延迟(秒)

  # 提示词版本配置（未指定时使用各任务默认最新版本）
  prompt_versions:
    classification: "v4"
    data_extraction: "v2"
    summarization: "v2"
    vqa: "v4"

  # 任务列表
  tasks:
#    - classification
#    - data_extraction
#    - summarization
    - vqa

# 评估配置
evaluation:
  # 任务列表
  tasks:
    - classification
    - data_extraction
    - summarization
    - vqa
  # 数据配置
  data:
    root: "/mnt/8T-1/lingzhou/Resource/ALD-E-ImageMiner-main/icdar2026-competition-data"
    split: "test"  # 评估数据集分割

  # 推理结果目录
  results_dir: "../../predictions/results_dev_gemini-3.1-pro_v3"

  # 评估输出目录
  output_dir: "/home/lingzhou/PythonProject/LM_WorkSpace/Sci-ImageMiner/src/eval/results_dev_gemini-3.1-pro_v3"

  # 分数阈值配置
  thresholds:
    # 分类任务阈值 (F1-score低于此值会被标记为差样本)
    classification:
      f1_threshold: 0.8

    # 数据抽取任务阈值 (TEDS低于此值会被标记为差样本)
    data_extraction:
      teds_threshold: 0.7
      rms_threshold: 0.6

    # 总结任务阈值 (ROUGE-L低于此值会被标记为差样本)
    summarization:
      rouge_l_threshold: 0.6
      bert_score_threshold: 0.85

    # VQA任务阈值
    vqa:
      # Yes/No类型
      yes_no:
        f1_threshold: 0.8
      # Factoid类型
      factoid:
        em_threshold: 0.7
        rouge_l_threshold: 0.6
      # List类型
      list:
        f1_threshold: 0.7
      # Paragraph类型
      paragraph:
        rouge_l_threshold: 0.6
        bert_score_threshold: 0.85
